services:
  web:
    container_name: bfi_viewer
    build: 
      context: .
      dockerfile:  Dockerfile
    volumes:
      - ./app:/app
    restart: always
    ports:
      - "${DOCKER_IP}:8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: bfi_viewer.settings
      DEBUG: "0"